name: Feature Request
description: Suggest a new feature or enhancement for GitHire
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Describe your ideal solution.
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions you've thought about...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of GitHire would this feature affect?
      options:
        - Frontend (React UI)
        - Backend API
        - JD Parser Module
        - GitHub Sourcer Module
        - Ranking Engine Module
        - Outreach Generator Module
        - Documentation
        - Infrastructure/DevOps
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: In your opinion, how complex would this feature be to implement?
      options:
        - Simple - Minor change or addition
        - Moderate - Requires some refactoring
        - Complex - Significant development effort
        - Very Complex - Major architectural changes
        - Not sure

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: |
        - Recruiters would benefit by...
        - Developers would benefit by...
        - The project would benefit by...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Do you have any mockups, screenshots, or examples from other tools?
      placeholder: Drag and drop images or paste links here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request
      placeholder: Any other relevant information...

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, I can help test"
        - "Yes, I can help with documentation"
        - "Maybe, with guidance"
        - "No, but I can provide feedback"

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have checked the roadmap to see if this is already planned
          required: true
        - label: I have provided all relevant information above
          required: true
